# fly.toml app configuration file generated for ekklesia on 2024-05-04T12:45:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ekklesia'
primary_region = 'sjc'

[build]

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
